export const allAnimes = [
    {
        id: 1,
        name: 'Camiseta Rengoku',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'demon slayer', 'demon', 'kimetsu no yaiba', 'kyojuro', 'rengoku', 'tanjiro','tanyiro', 'nezuko','nesuko', 'nesuco',' nezuco'],
        talla: ['XS', 'S', 'M'],
        precio: '$50.000',
        colores: [ 'Negro'],
        anime: 'demon slayer',
        cantidad: 5,
        url: '/images/demon/camisetas/camiseta_1.png',
    },
    {
        id: 2,
        name: 'Camiseta Nezuko',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'demon slayer', 'demon', 'kimetsu no yaiba', 'nezuko', 'nesuko', 'nesuco',' nezuco'],
        talla: ['XS', 'S', 'M'],
        precio: '$50.000',
        colores: [ 'Negro', 'Blanco', 'Azul'],
        anime: 'demon slayer',
        cantidad: 3,
        url: '/images/demon/camisetas/camiseta_2.png',
    },
    {
        id: 3,
        name: 'Camiseta Zenitsu',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'demon slayer', 'demon', 'kimetsu no yaiba', 'zenitsu', 'senitsu', 'zenitzu'],
        talla: [ 'S', 'M', 'L'],
        precio: '$50.000',
        colores: [ 'Negro', 'Amarillo'],
        anime: 'demon slayer',
        cantidad: 4,
        url: '/images/demon/camisetas/camiseta_3.png',
    },
    {
        id: 4,
        name: 'Camiseta Tanjiro',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'demon slayer', 'demon', 'kimetsu no yaiba', 'tanjiro', 'tanyiro'],
        talla: [ 'M', 'L'],
        precio: '$50.000',
        colores: [ 'Negro'],
        anime: 'demon slayer',
        cantidad: 2,
        url: '/images/demon/camisetas/camiseta_4.png',
    },
    {
        id: 5,
        name: 'Buso Demon slayer',
        descripcion: 'Buso hech en Algodon 100%. Con acabados de alta calidad. Producto 100% Colombiano. Todas nuestras camisetas cuentan con 6 meses de garantía.',
        keyWords: [ 'camiseta', 'buso', 'saco', 'chamarra', 'demon slayer', 'demon', 'kimetsu no yaiba', 'zenitsu', 'senitsu', 'zenitzu'],
        talla: [ 'S', 'M', 'L'],
        precio: '$120.000',
        colores: [ 'Negro', 'Amarillo'],
        anime: 'demon slayer',
        cantidad: 4,
        url: '/images/demon/camisetas/camiseta_5.png',
    },
    {
        id: 6,
        name: 'Figura Zenitsu',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'demon slayer', 'demon', 'kimetsu no yaiba', 'zenitsu', 'senitsu', 'zenitzu'],
        precio: '$170.000',
        anime: 'demon slayer',
        cantidad: 1,
        url: '/images/demon/figuras/Imagen 1.jpg',
    },
    {
        id: 7,
        name: 'Figura Tanjiro',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'demon slayer', 'demon', 'kimetsu no yaiba', 'tanjiro', 'kamado'],
        precio: '$170.000',
        anime: 'demon slayer',
        cantidad: 1,
        url: '/images/demon/figuras/imagen 2.jpg',
    },
    {
        id: 8,
        name: 'Figura Inozuke',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'demon slayer', 'demon', 'kimetsu no yaiba', 'inozque', 'inozke', 'inozuke'],
        precio: '$170.000',
        anime: 'demon slayer',
        cantidad: 1,
        url: '/images/demon/figuras/imagen 3.jpg',
    },
    {
        id: 9,
        name: 'Figura Nezuko',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'demon slayer', 'demon', 'kimetsu no yaiba', 'nesuko', 'nezuko'],
        precio: '$160.000',
        anime: 'demon slayer',
        cantidad: 1,
        url: '/images/demon/figuras/imagen 4.jpg',
    },
    {
        id: 10,
        name: 'Figura Tomioka',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'demon slayer', 'demon', 'kimetsu no yaiba', 'tomioka', 'tomioca'],
        precio: '$150.000',
        anime: 'demon slayer',
        cantidad: 1,
        url: '/images/demon/figuras/Imagen 5.jpg',
    },
    {
        id: 11,
        name: 'Llavero Kyojuro',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'demon slayer', 'demon', 'kimetsu no yaiba', 'rengoku', 'kyojuro'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 3,
        url: '/images/demon/llaveros/llavero 1.png',
    },
    {
        id: 12,
        name: 'Llavero Tomioka',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'demon slayer', 'demon', 'kimetsu no yaiba', 'tomioka', 'tomioca'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 2,
        url: '/images/demon/llaveros/llavero 2.png',
    },
    {
        id: 13,
        name: 'Llavero Zenitsu',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'demon slayer', 'demon', 'kimetsu no yaiba', 'zenitsu', 'senitsu'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 2,
        url: '/images/demon/llaveros/llavero 3.png',
    },
    {
        id: 14,
        name: 'Llavero Nezuko',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'demon slayer', 'demon', 'kimetsu no yaiba', 'nesuko', 'nezuko'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 3,
        url: '/images/demon/llaveros/llavero 4.png',
    },
    {
        id: 15,
        name: 'Llavero Muzan',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'demon slayer', 'demon', 'kimetsu no yaiba', 'muzan', 'demonio'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 3,
        url: '/images/demon/llaveros/llavero 5.png',
    },
    {
        id: 16,
        name: 'Case Tanjiro',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'demon slayer', 'demon', 'kimetsu no yaiba', 'tanjiro', 'tanyiro'],
        precio: '$35.000',
        anime: 'demon slayer',
        cantidad: 3,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/demon/stuches/stuche 1.png',
    },
    {
        id: 17,
        name: 'Case Zenitsu',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'demon slayer', 'demon', 'kimetsu no yaiba', 'zenitsu', 'senitsu'],
        precio: '$35.000',
        anime: 'demon slayer',
        cantidad: 4,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/demon/stuches/stuche 2.png',
    },
    {
        id: 18,
        name: 'Case Kocho',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'demon slayer', 'demon', 'kimetsu no yaiba', 'shinobu', 'kocho', 'cocho'],
        precio: '$35.000',
        anime: 'demon slayer',
        cantidad: 3,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/demon/stuches/stuche 3.png',
    },
    {
        id: 19,
        name: 'Case Muichiro',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'demon slayer', 'demon', 'kimetsu no yaiba', 'tokito', 'muichiro'],
        precio: '$35.000',
        anime: 'demon slayer',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/demon/stuches/stuche 4.png',
    },
    {
        id: 20,
        name: 'Case Nezuko',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'demon slayer', 'demon', 'kimetsu no yaiba', 'nesuko', 'nezuko'],
        precio: '$35.000',
        anime: 'demon slayer',
        cantidad: 4,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/demon/stuches/stuche 5.png',
    },
    {
        id: 21,
        name: 'Vaso Inozuke',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'demon slayer', 'demon', 'kimetsu no yaiba', 'inosuke', 'inozuke', 'inozque'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 5,
        url: '/images/demon/vasos/cup 1.jpg',
    },
    {
        id: 22,
        name: 'Vaso Tanjiro & Tomioka',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'demon slayer', 'demon', 'kimetsu no yaiba', 'tanjiro', 'tanyiro', 'tomioka', 'tomioca'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 4,
        url: '/images/demon/vasos/cup 2.jpg',
    },
    {
        id: 23,
        name: 'Vaso Cazadores',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'demon slayer', 'demon', 'kimetsu no yaiba', 'inosuke', 'inozuke', 'inozque', 'tanjiro', 'nezuko', 'zenitsu', 'kocho', 'shinobu', 'tomioka'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 3,
        url: '/images/demon/vasos/cup 3.jpg',
    },
    {
        id: 24,
        name: 'Vaso Zenitsu',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'demon slayer', 'demon', 'kimetsu no yaiba', 'zenitsu', 'senitsu'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 4,
        url: '/images/demon/vasos/cup 4.jpg',
    },
    {
        id: 25,
        name: 'Vaso Tanjiro & Nezuko',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'demon slayer', 'demon', 'kimetsu no yaiba', 'nezuko', 'nesuko', 'tanyiro', 'tanjiro'],
        precio: '$25.000',
        anime: 'demon slayer',
        cantidad: 2,
        url: '/images/demon/vasos/cup 5.jpg',
    },
    {
        id: 1,
        name: 'Camiseta Goku Ultrainstinto',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'dragon ball', 'goku', 'ultrainstinto'],
        talla: ['XS', 'S', 'M', 'L'],
        precio: '$50.000',
        colores: [ 'Negro'],
        anime: 'Dragon ball',
        cantidad: 5,
        url: '/images/dragon-ball/camisetas/1.png',
    },
    {
        id: 2,
        name: 'Camiseta Goku',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'dragon ball', 'goku'],
        talla: ['S', 'M', 'L'],
        precio: '$50.000',
        colores: [ 'Multicolor'],
        anime: 'Dragon ball',
        cantidad: 5,
        url: '/images/dragon-ball/camisetas/2.png',
    },
    {
        id: 3,
        name: 'Camiseta Gogueta SS4',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'dragon ball', 'goku', 'gogeta'],
        talla: ['S', 'M', 'L'],
        precio: '$50.000',
        colores: ['Multicolor'],
        anime: 'Dragon ball',
        cantidad: 5,
        url: '/images/dragon-ball/camisetas/3.png',
    },
    {
        id: 4,
        name: 'Camiseta Vegeta',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'dragon ball', 'vegeta', 'modo dios'],
        talla: ['S', 'M'],
        precio: '$50.000',
        colores: [ 'Negra', 'Gris'],
        anime: 'Dragon ball',
        cantidad: 5,
        url: '/images/dragon-ball/camisetas/4.png',
    },
    {
        id: 5,
        name: 'Camiseta Broly',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'dragon ball', 'broly'],
        talla: ['M', 'L', 'XL'],
        precio: '$50.000',
        colores: [ 'Azul', 'Negro'],
        anime: 'Dragon ball',
        cantidad: 5,
        url: '/images/dragon-ball/camisetas/5.png',
    },
    {
        id: 6,
        name: 'Figura Black Goku',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'dragon ball', 'black goku', 'rose'],
        precio: '$140.000',
        anime: 'Dragon ball',
        cantidad: 2,
        url: '/images/dragon-ball/figuras/1.jpg',
    },
    {
        id: 7,
        name: 'Figura Kid Boo',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'dragon ball','majin', 'majin bu', 'majin boo', 'boo', 'kid boo'],
        precio: '$150.000',
        anime: 'Dragon ball',
        cantidad: 1,
        url: '/images/dragon-ball/figuras/2.jpg',
    },
    {
        id: 8,
        name: 'Figura Broly',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'dragon ball', 'broly'],
        precio: '$160.000',
        anime: 'Dragon ball',
        cantidad: 1,
        url: '/images/dragon-ball/figuras/3.jpg',
    },
    {
        id: 9,
        name: 'Figura Vegeta',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'dragon ball', 'vegeta', 'blue', 'super sayayin blue'],
        precio: '$140.000',
        anime: 'Dragon ball',
        cantidad: 2,
        url: '/images/dragon-ball/figuras/4.jpg',
    },
    {
        id: 10,
        name: 'Figura Shen Long',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'dragon ball', 'goku', 'shenlong', 'dragon'],
        precio: '$160.000',
        anime: 'Dragon ball',
        cantidad: 2,
        url: '/images/dragon-ball/figuras/5.jpg',
    },
    {
        id: 11,
        name: 'Llavero Maestro Roshi',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'dragon ball', 'maestro', 'roshi', 'maestro roshi'],
        precio: '$25.000',
        anime: 'Dragon ball',
        cantidad: 3,
        url: '/images/dragon-ball/llaveros/1.jpg',
    },
    {
        id: 12,
        name: 'Llavero Vegeta',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'dragon ball', 'vegeta'],
        precio: '$15.000',
        anime: 'Dragon ball',
        cantidad: 5,
        url: '/images/dragon-ball/llaveros/2.jpg',
    },
    {
        id: 13,
        name: 'Llavero Picoro',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'dragon ball', 'piccolo', 'picoro' ],
        precio: '$15.000',
        anime: 'Dragon ball',
        cantidad: 5,
        url: '/images/dragon-ball/llaveros/3.jpg',
    },
    {
        id: 14,
        name: 'Llavero Kid Boo',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'dragon ball','majin bu','majin', 'majin boo', 'boo', 'kid boo'],
        precio: '$15.000',
        anime: 'Dragon ball',
        cantidad: 3,
        url: '/images/dragon-ball/llaveros/4.jpg',
    },
    {
        id: 15,
        name: 'Llavero Boo',
        descripcion: 'Producto 100% Colombiano, fabricados en polimeros y la cadenilla en acero inoxidable.',
        precio: '$15.000',
        keyWords: ['llavero', 'dragon ball','majin bu','majin', 'majin boo', 'boo', 'gordo'],
        anime: 'Dragon ball',
        cantidad: 3,
        url: '/images/dragon-ball/llaveros/5.jpg',
    },
    {
        id: 16,
        name: 'Case Goku Bardock',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'dragon ball', 'goku', 'bardock', 'ultrainstinto'],
        precio: '$35.000',
        anime: 'Dragon ball',
        cantidad: 7,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/dragon-ball/estuches/1-copy-0.jpg',
    },
    {
        id: 17,
        name: 'Case Goku',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'dragon ball', 'goku'],
        precio: '$35.000',
        anime: 'Dragon ball',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/dragon-ball/estuches/2.jpg',
    },
    {
        id: 18,
        name: 'Case Vegeta',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'dragon ball', 'vegeta', 'blue'],
        precio: '$35.000',
        anime: 'Dragon ball',
        cantidad: 4,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/dragon-ball/estuches/3.jpg',
    },
    {
        id: 19,
        name: 'Case Goku transformations',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'dragon ball', 'goku', 'transformaciones', 'miradas'],
        precio: '$35.000',
        anime: 'Dragon ball',
        cantidad: 3,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/dragon-ball/estuches/4.jpg',
    },
    {
        id: 20,
        name: 'Case Boo & Freezer',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'dragon ball', 'freezer','majin', 'majin bu', 'boo'],
        precio: '$35.000',
        anime: 'Dragon ball',
        cantidad: 6,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/dragon-ball/estuches/5-copy-0.jpg',
    },
    {
        id: 21,
        name: 'Vaso Vegeto, Goggeta',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'dragon ball', 'vegeto', 'vegueto', 'gogeta', 'gogueta', 'blue'],
        precio: '$25.000',
        anime: 'Dragon ball',
        cantidad: 3,
        url: '/images/dragon-ball/vasos/1-copy-1.jpg',
    },
    {
        id: 22,
        name: 'Vaso Goku transformations',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'dragon ball', 'goku', 'ultrainstinto', 'transformaciones'],
        precio: '$25.000',
        anime: 'Dragon ball',
        cantidad: 3,
        url: '/images/dragon-ball/vasos/2-copy-1.jpg',
    },
    {
        id: 23,
        name: 'Vaso Goku, Gohan',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'dragon ball', 'goku', 'gohan', 'sayayines'],
        precio: '$25.000',
        anime: 'Dragon ball',
        cantidad: 3,
        url: '/images/dragon-ball/vasos/3.jpg',
    },
    {
        id: 24,
        name: 'Vaso Krilin',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'dragon ball', 'krilin', 'krillin'],
        precio: '$25.000',
        anime: 'Dragon ball',
        cantidad: 8,
        url: '/images/dragon-ball/vasos/4-copy-0.jpg',
    },
    {
        id: 25,
        name: 'Vaso Bills',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'dragon ball', 'bills', 'dios de la destruccion'],
        precio: '$25.000',
        anime: 'Dragon ball',
        cantidad: 3,
        url: '/images/dragon-ball/vasos/5.jpg',
    },
    {
        id: 1,
        name: 'Camiseta Homero Drink',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'los simpson', 'simpsons', 'homero'],
        talla: ['S', 'M', 'L', 'XL'],
        precio: '$50.000',
        colores: [ 'Negro'],
        anime: 'los Simpson',
        cantidad: 3,
        url: '/images/los-simpsom/camisetas/1.jpg',
    },
    {
        id: 2,
        name: 'Camiseta Homero Marge',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'los simpson', 'simpsons', 'homero', 'marge'],
        talla: ['S', 'L', 'XL'],
        precio: '$50.000',
        colores: [ 'Negro', 'Blanco'],
        anime: 'los Simpson',
        cantidad: 5,
        url: '/images/los-simpsom/camisetas/2.jpg',
    },
    {
        id: 3,
        name: 'Camiseta Homero Donut',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'los simpson', 'simpsons', 'homero'],
        talla: ['S', 'M', 'XL'],
        precio: '$50.000',
        colores: [ 'Blanco'],
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/camisetas/3.jpg',
    },
    {
        id: 4,
        name: 'Camiseta Homero in love',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'los simpson', 'simpsons', 'homero'],
        talla: ['S', 'M', 'L'],
        precio: '$50.000',
        colores: [ 'Blanco'],
        anime: 'los Simpson',
        cantidad: 6,
        url: '/images/los-simpsom/camisetas/4.jpg',
    },
    {
        id: 5,
        name: 'Camiseta Homero Duff',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'los simpson', 'simpsons', 'homero'],
        talla: ['S', 'XL'],
        precio: '$50.000',
        colores: [ 'Negro'],
        anime: 'los Simpson',
        cantidad: 3,
        url: '/images/los-simpsom/camisetas/5.jpg',
    },
    {
        id: 6,
        name: 'Figura Flanders devil',
        descripcion: 'Figura polipropileno de alta densidad. Producto importado',
        keyWords: ['figura', 'los simpson', 'resina', 'muñeco', 'simpsons', 'flanders', 'ned'],
        precio: '$30.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/figuras/1.png',
    },
    {
        id: 7,
        name: 'Figura Lisa',
        descripcion: 'Figura polipropileno de alta densidad. Producto importado',
        keyWords: ['figura', 'los simpson', 'resina', 'muñeco', 'simpsons', 'lisa'],
        precio: '$30.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/figuras/2.png',
    },
    {
        id: 8,
        name: 'Figura Homero',
        descripcion: 'Figura polipropileno de alta densidad. Producto importado',
        keyWords: ['figura', 'los simpson', 'resina', 'muñeco', 'simpsons', 'homero'],
        precio: '$30.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/figuras/3.png',
    },
    {
        id: 9,
        name: 'Figura Maggie',
        descripcion: 'Figura polipropileno de alta densidad. Producto importado',
        keyWords: ['figura', 'los simpson', 'resina', 'muñeco', 'simpsons', 'maggie', 'magui', 'magi'],
        precio: '$30.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/figuras/4.png',
    },
    {
        id: 10,
        name: 'Figura Bart',
        descripcion: 'Figura polipropileno de alta densidad. Producto importado',
        keyWords: ['figura', 'los simpson', 'resina', 'muñeco', 'simpsons', 'bart'],
        precio: '$30.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/figuras/5.png',
    },
    {
        id: 11,
        name: 'Llavero Homero',
        descripcion: 'Producto importado, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'los simpson', 'simpsons', 'homero'],
        precio: '$10.000',
        anime: 'los Simpson',
        cantidad: 5,
        url: '/images/los-simpsom/llaveros/1.png',
    },
    {
        id: 12,
        name: 'Llavero Bart',
        descripcion: 'Producto importado, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'los simpson', 'simpsons', 'bart'],
        precio: '$10.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/llaveros/2.png',
    },
    {
        id: 13,
        name: 'Llavero Cerveza Duff',
        descripcion: 'Producto importado, fabricados en polimeros y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'los simpson', 'simpsons', 'duff', 'cerveza'],
        precio: '$10.000',
        anime: 'los Simpson',
        cantidad: 3,
        url: '/images/los-simpsom/llaveros/3.jpg',
    },
    {
        id: 14,
        name: 'Llavero Dona',
        descripcion: 'Producto importado, fabricado en polipropileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'los simpson', 'simpsons', 'dona', 'donut'],
        precio: '$30.000',
        anime: 'los Simpson',
        cantidad: 3,
        url: '/images/los-simpsom/llaveros/4.jpg',
    },
    {
        id: 15,
        name: 'Llavero Familia Simpson',
        descripcion: 'Producto importado, fabricados en polipropileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'los simpson', 'simpsons', 'homero', 'bart', 'marge', 'lisa'],
        precio: '$25.000',
        anime: 'los Simpson',
        cantidad: 5,
        url: '/images/los-simpsom/llaveros/5.jpg',
    },
    {
        id: 16,
        name: 'Case Homero',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'los simpson', 'estuche', 'simpsons', 'homero'],
        precio: '$35.000',
        anime: 'los Simpson',
        cantidad: 4,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/los-simpsom/stuches/1.jpg',
    },
    {
        id: 17,
        name: 'Case Homero',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'los simpson', 'estuche', 'simpsons', 'homero'],
        precio: '$35.000',
        anime: 'los Simpson',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/los-simpsom/stuches/2.png',
    },
    {
        id: 18,
        name: 'Case Homero & Marge',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'los simpson', 'estuche', 'simpsons', 'homero', 'marge'],
        precio: '$35.000',
        anime: 'los Simpson',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/los-simpsom/stuches/3.png',
    },
    {
        id: 19,
        name: 'Case Bart , Maggie, Lisa',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'los simpson', 'estuche', 'simpsons', 'bart', 'lisa', 'maggie'],
        precio: '$35.000',
        anime: 'los Simpson',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/los-simpsom/stuches/4.png',
    },
    {
        id: 20,
        name: 'Case Familia Simpson',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'los simpson', 'estuche', 'simpsons', 'homero', 'bart', 'lisa', 'marge', 'maggie'],
        precio: '$35.000',
        anime: 'los Simpson',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/los-simpsom/stuches/5.jpg',
    },
    {
        id: 21,
        name: 'Vaso Bart',
        descripcion: 'Vasos fabricados en polietileno. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para bebidas frias.',
        keyWords: ['vaso', 'los simpson', 'simpsons', 'bart'],
        precio: '$25.000',
        anime: 'los Simpson',
        cantidad: 3,
        url: '/images/los-simpsom/vasos/1.png',
    },
    {
        id: 22,
        name: 'Vaso Homero',
        descripcion: 'Vasos fabricados ceramica. Perfectos para bebidas frias y calientes. En especial para cerveza.',
        keyWords: ['vaso', 'los simpson', 'simpsons', 'Homero'],
        precio: '$35.000',
        anime: 'los Simpson',
        cantidad: 5,
        url: '/images/los-simpsom/vasos/2.png',
    },
    {
        id: 23,
        name: 'Vaso Moe & Barnie',
        descripcion: 'Vasos fabricados en polietileno. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para bebidas frias.',
        keyWords: ['vaso', 'los simpson', 'simpsons', 'moe', 'barnie'],
        precio: '$25.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/vasos/3.png',
    },
    {
        id: 24,
        name: 'Vaso Homero',
        descripcion: 'Vasos fabricados en polietileno. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para bebidas frias.',
        keyWords: ['vaso', 'los simpson', 'simpsons', 'Homero'],
        precio: '$25.000',
        anime: 'los Simpson',
        cantidad: 4,
        url: '/images/los-simpsom/vasos/4.png',
    },
    {
        id: 25,
        name: 'Vaso Homero Buda',
        descripcion: 'Vasos fabricados en polietileno. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para bebidas frias.',
        keyWords: ['vaso', 'los simpson', 'simpsons', 'Homero'],
        precio: '$25.000',
        anime: 'los Simpson',
        cantidad: 3,
        url: '/images/los-simpsom/vasos/5.png',
    },
    {
        id: 1,
        name: 'Camiseta Mario Y Luigi',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'mario', 'luigi'],
        talla: [ 'S', 'M', 'L'],
        precio: '$50.000',
        colores: [ 'Negro', 'Azul', 'Rojo' ],
        anime: 'Mario',
        cantidad: 7,
        url: '/images/Mario/camisetas/3.png',
    },
    {
        id: 2,
        name: 'Camibuso Mario Y Luigi',
        descripcion: 'Camibuso  hecho en Algodon 100%. Con acabados de alta calidad. Producto 100% Colombiano. Todas nuestras camisetas cuentan con 6 meses de garantía.',
        keyWords: ['camiseta', 'buso', 'saco','camibuso', 'mario', 'luigi'],
        talla: [ 'S', 'M', 'L', 'XL'],
        precio: '$80.000',
        colores: [ 'Negro', 'Azul', 'Verde' ],
        anime: 'Mario',
        cantidad: 4,
        url: '/images/Mario/camisetas/4.png',
    },
    {
        id: 3,
        name: 'Camiseta Mario Y Donkey kong',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'mario', 'luigi', 'kong', 'jhoshi', 'yoshi'],
        talla: [ 'S', 'M'],
        precio: '$50.000',
        colores: [ 'Negro', 'Verde', 'Rojo' ],
        anime: 'Mario',
        cantidad: 4,
        url: '/images/Mario/camisetas/5.png',
    },
    {
        id: 4,
        name: 'Buso Mario Y Pokemon',
        descripcion: 'Buso hecho en Algodon 100%.Con acabados de alta calidad. Producto 100% Colombiano. Todas nuestras camisetas cuentan con 6 meses de garantía.',
        keyWords: ['camiseta', 'buso', 'saco', 'mario', 'pokemon', 'peaches'],
        talla: [ 'S', 'L'],
        precio: '$90.000',
        colores: [ 'Multicolor' ],
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/camisetas/buso 1.png',
    },
    {
        id: 5,
        name: 'Buso Varios',
        descripcion: 'Buso hecho en Algodon 100%.Con acabados de alta calidad. Producto 100% Colombiano. Todas nuestras camisetas cuentan con 6 meses de garantía.',
        keyWords: ['camiseta', 'buso', 'saco', 'mario', 'pokemon', 'peaches', 'zelda', 'megaman', 'sonic'],
        talla: [ 'S', 'M', 'L'],
        precio: '$100.000',
        colores: [ 'Multicolor'],
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/camisetas/buso 2.png',
    },
    {
        id: 6,
        name: 'Figura Bowser',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'mario', 'bowser', 'tortuga', 'dragon'],
        precio: '$80.000',
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/figuras/figura-1.png',
    },
    {
        id: 7,
        name: 'Figura Luigi',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'mario', 'luigi'],
        precio: '$80.000',
        anime: 'Mario',
        cantidad: 2,
        url: '/images/Mario/figuras/figura-2.png',
    },
    {
        id: 8,
        name: 'Figura Toad (honguito)',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'mario', 'toad', 'honguito'],
        precio: '$90.000',
        anime: 'Mario',
        cantidad: 1,
        url: '/images/Mario/figuras/figura-3.png',
    },
    {
        id: 9,
        name: 'Figura Princesa Peach',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'mario', 'peach', 'princesa'],
        precio: '$90.000',
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/figuras/figura-4.png',
    },
    {
        id: 10,
        name: 'Figura Mario',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['resina', 'muñeco', 'figura', 'mario'],
        precio: '$100.000',
        anime: 'Mario',
        cantidad: 1,
        url: '/images/Mario/figuras/figura-5.png',
    },
    {
        id: 11,
        name: 'Llavero Mario & Luigi',
        descripcion: 'Producto importado, fabricado en polipropileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'mario', 'luigi'],
        precio: '$30.000',
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/llaveros/1.jpg',
    },
    {
        id: 12,
        name: 'Llavero Mario',
        descripcion: 'Producto importado, fabricado en polipropileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'mario'],
        precio: '$20.000',
        anime: 'Mario',
        cantidad: 2,
        url: '/images/Mario/llaveros/2.jpg',
    },
    {
        id: 13,
        name: 'Llavero Bowser',
        descripcion: 'Producto importado, fabricado en polipropileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'mario', 'bowser', 'tortuga', 'dragon'],
        precio: '$15.000',
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/llaveros/3.jpg',
    },
    {
        id: 14,
        name: 'Llavero Tortuga',
        descripcion: 'Producto importado, fabricado en polipropileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'mario', 'tortuga', 'dragon'],
        precio: '$25.000',
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/llaveros/4.jpg',
    },
    {
        id: 15,
        name: 'Llavero Luigi',
        descripcion: 'Producto importado, fabricado en polipropileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'mario', 'luigi'],
        precio: '$20.000',
        anime: 'Mario',
        cantidad: 2,
        url: '/images/Mario/llaveros/5.jpg',
    },
    {
        id: 16,
        name: 'Case Super Mario Bros',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'mario', 'nintendo'],
        precio: '$35.000',
        anime: 'Mario',
        cantidad: 4,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/Mario/stuches/1.png',
    },
    {
        id: 17,
        name: 'Case Mario',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'mario'],
        precio: '$35.000',
        anime: 'Mario',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/Mario/stuches/2.png',
    },
    {
        id: 18,
        name: 'Case Luigi',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'mario', 'luigi'],
        precio: '$35.000',
        anime: 'Mario',
        cantidad: 3,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/Mario/stuches/3.png',
    },
    {
        id: 19,
        name: 'Case Mario',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'mario'],
        precio: '$35.000',
        anime: 'Mario',
        cantidad: 4,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/Mario/stuches/4.png',
    },
    {
        id: 20,
        name: 'Case Mario World',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'estuche', 'mario', 'luigi'],
        precio: '$35.000',
        anime: 'Mario',
        cantidad: 2,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/Mario/stuches/5.png',
    },
    {
        id: 21,
        name: 'Vaso Bowser',
        descripcion: 'Vasos fabricados en ceramica con pintura acrilica. Perfectos para bebidas frias y calientes.',
        keyWords: ['vaso', 'mario', 'bowser', 'tortuga', 'dragon'],
        precio: '$25.000',
        anime: 'Mario',
        cantidad: 3,
        url: '/images/Mario/vasos/taza_1.png',
    },
    {
        id: 22,
        name: 'Vaso Luigi',
        descripcion: 'Vasos fabricados en polietileno. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para bebidas frias.',
        keyWords: ['vaso', 'mario', 'luigi'],
        precio: '$20.000',
        anime: 'Mario',
        cantidad: 5,
        url: '/images/Mario/vasos/taza_2.png',
    },
    {
        id: 23,
        name: 'Vaso Mario Game',
        descripcion: 'Vasos fabricados en ceramica con pintura acrilica. Perfectos para bebidas frias y calientes.',
        keyWords: ['vaso', 'mario', 'luigi'],
        precio: '$40.000',
        anime: 'Mario',
        cantidad: 2,
        url: '/images/Mario/vasos/taza_3.png',
    },
    {
        id: 24,
        name: 'Vaso Mario',
        descripcion: 'Vasos fabricados en ceramica con pintura acrilica. Perfectos para bebidas frias y calientes.',
        keyWords: ['vaso', 'mario'],
        precio: '$20.000',
        anime: 'Mario',
        cantidad: 4,
        url: '/images/Mario/vasos/taza_4.png',
    },
    {
        id: 25,
        name: 'Vaso Mario & Luigi',
        descripcion: 'Vasos fabricados en ceramica con pintura acrilica. Perfectos para bebidas frias y calientes.',
        keyWords: ['vaso', 'mario', 'luigi'],
        precio: '$25.000',
        anime: 'Mario',
        cantidad: 5,
        url: '/images/Mario/vasos/taza_5.png',
    },
    {
        id: 1,
        name: 'Camiseta 7 Pecados',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'ban', 'diana', 'meliodas','king', 'gowther','elizabeth'],
        talla: ['XS', 'S', 'M', 'L'],
        precio: '$50.000',
        colores: [ 'Negro', 'Blanco'],
        anime: 'seven deadly',
        cantidad: 5,
        url: '/images/the-seven-deadly/camisetas/1.png',
    },
    {
        id: 2,
        name: 'Camiseta 7 Pecados',
        descripcion: 'Camiseta  hecha en Algodon 80% y Poliéster 20%. Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'ban', 'diana', 'meliodas','king', 'gowther','elizabeth'],
        talla: ['XS', 'L', 'XL'],
        precio: '$50.000',
        colores: [ 'Blanco'],
        anime: 'seven deadly',
        cantidad: 3,
        url: '/images/the-seven-deadly/camisetas/2.png',
    },
    {
        id: 3,
        name: 'Buso Ban',
        descripcion: 'Buso hecho en Algodon 100%.Con acabados de alta calidad. Producto 100% Colombiano.',
        keyWords: ['camiseta', 'nanatsu no taizai', 'buso', 'saco', 'sudadera', 'seven deadly', 'siete pecados', 'ban', 'el zorro'],
        talla: ['M', 'L'],
        precio: '$110.000',
        colores: [ 'Vinotinto'],
        anime: 'seven deadly',
        cantidad: 3,
        url: '/images/the-seven-deadly/camisetas/3.png',
    },
    {
        id: 4,
        name: 'Camiseta Ban el zorro',
        descripcion: 'Camiseta  hecha en Algodon 100%.Con acabados de alta calidad. Producto 100% Colombiano. Todas nuestras camisetas cuentan con 6 meses de garantía.',
        keyWords: ['camiseta', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'ban', 'el zorro'],
        talla: ['XS', 'S', 'L'],
        precio: '$50.000',
        colores: [ 'Negro', 'Amarillo'],
        anime: 'seven deadly',
        cantidad: 2,
        url: '/images/the-seven-deadly/camisetas/4.png',
    },
    {
        id: 5,
        name: 'Camibuso Meliodas',
        descripcion: 'Camibuso  hecho en Algodon 100%.Con acabados de alta calidad. Producto 100% Colombiano. Todas nuestras camisetas cuentan con 6 meses de garantía.',
        keyWords: ['camiseta', 'nanatsu no taizai', 'buso', 'saco', 'sudadera', 'seven deadly', 'siete pecados', 'meliodas'],
        talla: ['M', 'L'],
        precio: '$70.000',
        colores: [ 'Negro'],
        anime: 'seven deadly',
        cantidad: 1,
        url: '/images/the-seven-deadly/camisetas/5.png',
    },
    {
        id: 6,
        name: 'Figura Meliodas',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['figura', 'nanatsu no taizai', 'resina', 'muñeco', 'seven deadly', 'siete pecados', 'meliodas'],
        precio: '$130.000',
        anime: 'seven deadly',
        cantidad: 2,
        url: '/images/the-seven-deadly/figuras/1.png',
    },
    {
        id: 7,
        name: 'Figura Ban vs King',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['figura', 'nanatsu no taizai', 'resina', 'muñeco', 'seven deadly', 'siete pecados', 'ban', 'king'],
        precio: '$150.000',
        anime: 'seven deadly',
        cantidad: 1,
        url: '/images/the-seven-deadly/figuras/2.png',
    },
    {
        id: 8,
        name: 'Figura Elizabeth',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['figura', 'nanatsu no taizai', 'resina', 'muñeco', 'seven deadly', 'siete pecados', 'elizabeth'],
        precio: '$110.000',
        anime: 'seven deadly',
        cantidad: 2,
        url: '/images/the-seven-deadly/figuras/3.png',
    },
    {
        id: 9,
        name: 'Figura Ban',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['figura', 'nanatsu no taizai', 'resina', 'muñeco', 'seven deadly', 'siete pecados', 'ban'],
        precio: '$130.000',
        anime: 'seven deadly',
        cantidad: 2,
        url: '/images/the-seven-deadly/figuras/4.png',
    },
    {
        id: 10,
        name: 'Figura king',
        descripcion: 'Figura hecha en resina de alta calidad, con pintura artistica. Producto importado',
        keyWords: ['figura', 'nanatsu no taizai', 'resina', 'muñeco', 'seven deadly', 'siete pecados', 'king', 'rey hada'],
        precio: '$130.000',
        anime: 'seven deadly',
        cantidad: 2,
        url: '/images/the-seven-deadly/figuras/5.png',
    },
    {
        id: 11,
        name: 'Tesoro sagrado Escanor',
        descripcion: 'Producto importado, fabricado en acero y polietileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'escanor', 'tesoro sagrado'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 3,
        url: '/images/the-seven-deadly/llaveros/1.jpg',
    },
    {
        id: 12,
        name: 'Tesoro sagrado Diana',
        descripcion: 'Producto importado, fabricado en acero y polietileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'diana', 'tesoro sagrado'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 4,
        url: '/images/the-seven-deadly/llaveros/2.jpg',
    },
    {
        id: 13,
        name: 'Tesoro sagrado King',
        descripcion: 'Producto importado, fabricado en acero y polietileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'king', 'tesoro sagrado'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 2,
        url: '/images/the-seven-deadly/llaveros/3.jpg',
    },
    {
        id: 14,
        name: 'Tesoro sagrado Meliodas',
        descripcion: 'Producto importado, fabricado en acero y polietileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'meliodas', 'tesoro sagrado'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 4,
        url: '/images/the-seven-deadly/llaveros/4.jpg',
    },
    {
        id: 15,
        name: 'Llavero daga Meliodas',
        descripcion: 'Producto importado, fabricado en acero y polietileno y la cadenilla en acero inoxidable.',
        keyWords: ['llavero', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'meliodas', 'tesoro sagrado'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 3,
        url: '/images/the-seven-deadly/llaveros/5.jpg',
    },
    {
        id: 16,
        name: 'Case Meliodas',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'nanatsu no taizai', 'estuche', 'seven deadly', 'siete pecados', 'meliodas'],
        precio: '$35.000',
        anime: 'seven deadly',
        cantidad: 4,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/the-seven-deadly/stuches/1.png',
    },
    {
        id: 17,
        name: 'Case Meliodas',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'nanatsu no taizai', 'estuche', 'seven deadly', 'siete pecados', 'meliodas'],
        precio: '$35.000',
        anime: 'seven deadly',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/the-seven-deadly/stuches/2.png',
    },
    {
        id: 18,
        name: 'Case 7 Pecados',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'nanatsu no taizai', 'estuche', 'seven deadly', 'siete pecados', 'meliodas', 'ban', 'king', 'elizabeth', 'diana', 'gowther', 'merlin'],
        precio: '$35.000',
        anime: 'seven deadly',
        cantidad: 3,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/the-seven-deadly/stuches/3.png',
    },
    {
        id: 19,
        name: 'Case Ban',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'nanatsu no taizai', 'estuche', 'seven deadly', 'siete pecados', 'ban'],
        precio: '$35.000',
        anime: 'seven deadly',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/the-seven-deadly/stuches/4.png',
    },
    {
        id: 20,
        name: 'Case 7 pecados',
        descripcion: 'Nuestros cases son fabricados y adapatados para casi cualquier referencia de celular. Con diseños propios o tambien personalizables a tu gusto.',
        keyWords: ['case', 'nanatsu no taizai', 'estuche', 'seven deadly', 'siete pecados', 'meliodas', 'ban', 'king', 'elizabeth', 'diana', 'gowther', 'merlin'],
        precio: '$35.000',
        anime: 'seven deadly',
        cantidad: 5,
        celulares: ['Samsung', 'Xiaomi', 'Apple', 'Oppo', 'Huawei', 'etc'],
        url: '/images/the-seven-deadly/stuches/5.png',
    },
    {
        id: 21,
        name: 'Vaso Escanor',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'escanor'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 3,
        url: '/images/the-seven-deadly/vasos/1.jpg',
    },
    {
        id: 22,
        name: 'Vaso Ban',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'ban'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 4,
        url: '/images/the-seven-deadly/vasos/2.jpg',
    },
    {
        id: 23,
        name: 'Vaso Diana',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'diana'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 5,
        url: '/images/the-seven-deadly/vasos/3.jpg',
    },
    {
        id: 24,
        name: 'Vaso Elizabeth',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'elizabeth'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 3,
        url: '/images/the-seven-deadly/vasos/4.jpg',
    },
    {
        id: 25,
        name: 'Vaso Zeldris',
        descripcion: 'Vasos fabricados en acero inoxidable. Vienen con tapa para hermetizar y evitar derrames de liquido. Perfectos para cualquier tipo de bebida.',
        keyWords: ['vaso', 'nanatsu no taizai', 'seven deadly', 'siete pecados', 'zeldris'],
        precio: '$25.000',
        anime: 'seven deadly',
        cantidad: 2,
        url: '/images/the-seven-deadly/vasos/5.jpg',
    },
]